---
language: python
python: "2.7"
branches:
  only:
    - master

sudo: required
dist: trusty

services:
  - docker

env:
  - DB=sqlite

install:
  - ./travis-ci/install.sh $DB

script:
  - cd travis-ci && ./run_tests.sh